spring:
  application:
    name: customers

server:
  port: 9000

integration:
  stores:
    uri: http://localhost:8081
    test: '{cipher}316f8cdbb776c23e679bf209014788a6eab7522f48f97114328c2c9388e6b3c1'

stores:
  ribbon:
    ServerListRefreshInterval: 1000

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    region: default
    registryFetchIntervalSeconds: 5
    availabilityZones: 
      default: ${APPLICATION_DOMAIN:${DOMAIN:defaultZone}}

# For demo only allow more hystrix connections
hystrix:
  stream:
    maxConcurrentConnections: 20

logging:
  level:
    com.netflix.discovery: 'OFF'